"""empty message

Revision ID: 68760ec51c29
Revises: 46184a3ad094
Create Date: 2021-11-23 15:52:13.446947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68760ec51c29'
down_revision = '46184a3ad094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
